version: '3.8'

services:
  # Test runner service
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        SERVICE: ${TEST_SERVICE:-all}
    volumes:
      - .:/app
    working_dir: /app
    command: echo "Tests completed"

  # Test with infrastructure
  test-integration:
    image: golang:1.23-alpine
    depends_on:
      - postgres-test
      - redis-test
    environment:
      DATABASE_HOST: postgres-test
      DATABASE_PORT: 5432
      DATABASE_USER: test
      DATABASE_PASSWORD: test
      DATABASE_NAME: test_db
      REDIS_ADDR: redis-test:6379
    volumes:
      - .:/app
    working_dir: /app
    command: |
      sh -c "
        apk add --no-cache git make &&
        cd shared && go test ./... -v && cd .. &&
        cd services/analysis && go test ./... -v && cd ../.. &&
        cd services/api-gateway && go test ./... -v
      "

  # Test infrastructure
  postgres-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"

  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"